import Head from 'next/head';
import HeaderNavBar from 'src/components/navbars/HeaderNavbar';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HeaderNavBar />
      <main></main>

      <footer></footer>
    </>
  );
}
