import * as React from 'react';
import Head from 'next/head';

import MainNavbar from 'src/components/navbars/MainNavbar';
import UserSignIn from 'src/components/UserSignIn';
import ParticleBackground from 'src/components/particleBackground';

export default function SignIn() {
  return (
    <React.Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ParticleBackground />
      <MainNavbar />
      <main>
        <UserSignIn />
      </main>
    </React.Fragment>
  );
}
