import * as React from 'react';
import Head from 'next/head';
import {
  CodeIcon,
  CogIcon,
  ClipboardListIcon,
  ScaleIcon,
  DocumentTextIcon,
} from '@heroicons/react/outline';

import MainNavbar from 'src/components/navbars/MainNavbar';
import MainFooter from 'src/components/MainFooter';
import HomePageSvg from 'src/svgs/homepageSVG';

export default function Home() {
  return (
    <React.Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainNavbar />
      <main>
        <div className="rounded-3xl max-w-7xl h-3/4 drop-shadow-none z-10 lg:flex mx-auto bg-inherit md:justify-center md:items-center my-10 md:my-20 ">
          <div className="w-auto md:mx-auto md:w-3/4 lg:w-1/2 p-10">
            <h1 className="text-4xl mb-7 lg:text-5xl md:leading-normal font-bold ">
              <span className="text-slate-800 dark:text-white">
                We make your business look good
              </span>{' '}
              <span className="text-blue-600">online.</span>
            </h1>
            <p className="text-xl mt-4">
              {' '}
              Offering scalable and manageable web development solutions with
              the latest technology to let your business have a unique online
              representation.{' '}
            </p>
          </div>
          <div className="w-1/2 p-10 h-3/4 hidden lg:flex justify-center items-center">
            <HomePageSvg height="500" width="500" />
          </div>
        </div>
        <section className=" md:mt-52 mt-52 max-w-full mx-auto pb-32 relative bg-slate-100 dark:bg-gray-900">
          <div
            className="-mt-20 top-0 bottom-auto left-0 right-0 w-full absolute"
            style={{ height: '80px' }}
          >
            <svg
              className="absolute bottom-0 overflow-hidden"
              xmlns="http://www.w3.org/2000/svg"
              preserveAspectRatio="none"
              version="1.1"
              viewBox="0 0 2560 100"
              x="0"
              y="0"
            >
              <polygon
                className="text-slate-100 dark:text-gray-900 fill-current"
                points="2560 0 2560 100 0 100"
              ></polygon>
            </svg>
          </div>
          <div />
          <div className="container mx-auto mt-30">
            <div className="flex flex-wrap items-center">
              <div className="w-11/12 md:w-6/12 lg:w-4/12 px-12 md:px-4 mr-auto ml-auto -mt-32">
                <div className="relative flex flex-col min-w-0 break-words w-full mb-6 shadow-lg rounded-lg bg-blue-500">
                  <img
                    alt="..."
                    src="/macbook_index.png"
                    className="w-full align-middle rounded-t-lg"
                  />
                  <blockquote className="relative p-8 mb-4">
                    <svg
                      preserveAspectRatio="none"
                      xmlns="http://www.w3.org/2000/svg"
                      viewBox="0 0 583 95"
                      className="absolute left-0 w-full block"
                      style={{ height: '95px', top: '-94px' }}
                    >
                      <polygon
                        points="-30,95 583,95 583,65"
                        className="text-blue-500 fill-current"
                      ></polygon>
                    </svg>
                    <h4 className="text-xl font-bold text-white">
                      Great for your awesome project
                    </h4>
                    <p className="text-md font-light mt-2 text-white">
                      Putting together a page has never been easier than
                      matching together pre-made components. From landing pages
                      presentation to login areas, you can easily customise and
                      built your pages.
                    </p>
                  </blockquote>
                </div>
              </div>
              <div className="w-full md:w-6/12 px-4">
                <div className="flex flex-wrap">
                  <div className="w-full md:w-6/12 px-4">
                    <div className="relative flex flex-col mt-4">
                      <div className="px-4 py-5 flex-auto">
                        <div className="text-slate-500 p-3 text-center inline-flex items-center justify-center w-12 h-12 mb-5 shadow-lg rounded-full bg-white dark:bg-black border-2 border-blue-500">
                          <CogIcon />
                        </div>
                        <h6 className="text-xl mb-1 font-semibold">
                          CSS Components
                        </h6>
                        <p className="mb-4 text-slate-500">
                          Tailwind Starter Kit comes with a huge number of Fully
                          Coded CSS components.
                        </p>
                      </div>
                    </div>
                    <div className="relative flex flex-col min-w-0">
                      <div className="px-4 py-5 flex-auto">
                        <div className="text-slate-500 p-3 text-center inline-flex items-center justify-center w-12 h-12 mb-5 shadow-lg rounded-full bg-white dark:bg-black border-2 border-blue-500">
                          <ClipboardListIcon />
                        </div>
                        <h6 className="text-xl mb-1 font-semibold">
                          JavaScript Components
                        </h6>
                        <p className="mb-4 text-slate-500">
                          We also feature many dynamic components for React, Vue
                          and Angular.
                        </p>
                      </div>
                    </div>
                  </div>
                  <div className="w-full md:w-6/12 px-4">
                    <div className="relative flex flex-col min-w-0 mt-4">
                      <div className="px-4 py-5 flex-auto">
                        <div className="text-slate-500 p-3 text-center inline-flex items-center justify-center w-12 h-12 mb-5 shadow-lg rounded-full bg-white dark:bg-black border-2 border-blue-500">
                          <ScaleIcon />
                        </div>
                        <h6 className="text-xl mb-1 font-semibold">Pages</h6>
                        <p className="mb-4 text-slate-500">
                          This extension also comes with 3 sample pages. They
                          are fully coded so you can start working instantly.
                        </p>
                      </div>
                    </div>
                    <div className="relative flex flex-col min-w-0">
                      <div className="px-4 py-5 flex-auto">
                        <div className="text-slate-500 p-3 text-center inline-flex items-center justify-center w-12 h-12 mb-5 shadow-lg rounded-full bg-white dark:bg-black border-2 border-blue-500">
                          <DocumentTextIcon />
                        </div>
                        <h6 className="text-xl mb-1 font-semibold">
                          Documentation
                        </h6>
                        <p className="mb-4 text-slate-500">
                          Built by developers for developers. You will love how
                          easy is to to work with Tailwind Starter Kit.
                        </p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="container mx-auto overflow-hidden pb-20">
            <div className="flex flex-wrap items-center lg:pt-24">
              <div className="w-full md:w-6/12 px-4 mr-auto ml-auto mt-32">
                <div className="justify-center flex flex-wrap relative">
                  <div className="my-4 w-full lg:w-6/12 px-4">
                    <div className="bg-sky-500 shadow-lg rounded-lg text-center p-8">
                      <img
                        alt="..."
                        className="shadow-md rounded-full max-w-full w-16 mx-auto p-2 bg-white"
                        src="/react_index.png"
                      />
                      <noscript>
                        <img
                          alt="..."
                          className="shadow-md rounded-full max-w-full w-16 mx-auto p-2 bg-white"
                          src="/react_index.png"
                        />
                      </noscript>
                      <p className="text-lg text-white mt-4 font-semibold">
                        ReactJS
                      </p>
                      <p className="text-base text-white opacity-75 mt-2">
                        A JavaScript library for building user interfaces
                        maintaned by Facebook and community of developers.
                      </p>
                    </div>
                    <div className="bg-emerald-500 shadow-lg rounded-lg text-center p-8 mt-8">
                      <img
                        alt="..."
                        className="shadow-md rounded-full max-w-full w-16 mx-auto p-2 bg-white"
                        src="/vue_index.png"
                      />
                      <noscript>
                        <img
                          alt="..."
                          className="shadow-md rounded-full max-w-full w-16 mx-auto p-2 bg-white"
                          src="/vue_index.png"
                        />
                      </noscript>
                      <p className="text-lg text-white mt-4 font-semibold">
                        Vue.js
                      </p>
                      <p className="text-base text-white opacity-75 mt-2">
                        An open-source Model-view-viewmodel JavaScript framework
                        for building user interfaces.
                      </p>
                    </div>
                  </div>
                  <div className="my-4 w-full lg:w-6/12 px-4 lg:mt-16">
                    <div className="bg-orange-500 shadow-lg rounded-lg text-center p-8">
                      <img
                        alt="..."
                        className="shadow-md rounded-full max-w-full w-16 mx-auto p-2 bg-white"
                        src="javascript_index.png"
                      />
                      <noscript>
                        <img
                          alt="..."
                          className="shadow-md rounded-full max-w-full w-16 mx-auto p-2 bg-white"
                          src="javascript_index.png"
                        />
                      </noscript>
                      <p className="text-lg text-white mt-4 font-semibold">
                        JavaScript
                      </p>
                      <p className="text-base text-white opacity-75 mt-2">
                        Object-oriented programming language that conforms to
                        the ECMAScript specification.
                      </p>
                    </div>
                    <div className="bg-red-600 shadow-lg rounded-lg text-center p-8 mt-8">
                      <img
                        alt="..."
                        className="shadow-md rounded-full max-w-full w-16 mx-auto p-2 bg-white"
                        src="/angular_index.png"
                      />
                      <noscript>
                        <img
                          alt="..."
                          className="shadow-md rounded-full max-w-full w-16 mx-auto p-2 bg-white"
                          src="angular_index.png"
                        />
                      </noscript>
                      <p className="text-lg text-white mt-4 font-semibold">
                        Angular
                      </p>
                      <p className="text-base text-white opacity-75 mt-2">
                        a JavaScript-based open-source front-end web framework
                        mainly maintained by Google.
                      </p>
                    </div>
                  </div>
                </div>
              </div>
              <div className="w-full md:w-4/12 px-12 md:px-4 ml-auto mr-auto mt-48">
                <div className="text-blue-500 border-2 border-blue-500 p-3 text-center inline-flex items-center justify-center w-16 h-16 mb-6 shadow-lg rounded-full bg-white dark:bg-black">
                  <CodeIcon className="w-8" />
                </div>
                <h3 className="text-3xl mb-2 font-semibold leading-normal">
                  Javascript Components
                </h3>
                <p className="text-lg font-light leading-relaxed mt-4 mb-4 text-slate-600 dark:text-slate-300">
                  In order to create a great User Experience some components
                  require JavaScript. In this way you can manipulate the
                  elements on the page and give more options to your users.
                </p>
                <p className="text-lg font-light leading-relaxed mt-4 mb-4 text-slate-600 dark:text-slate-300">
                  We created a set of Components that are dynamic and come to
                  help you.
                </p>
                <div className="block pb-6">
                  <span className="text-xs font-semibold inline-block py-1 px-2 rounded-full text-slate-500 bg-white dark:bg-black dark:text-blue-500 uppercase last:mr-0 mr-2 mt-2">
                    Alerts
                  </span>
                  <span className="text-xs font-semibold inline-block py-1 px-2 rounded-full text-slate-500 bg-white dark:bg-black dark:text-blue-500 uppercase last:mr-0 mr-2 mt-2">
                    Dropdowns
                  </span>
                  <span className="text-xs font-semibold inline-block py-1 px-2 rounded-full text-slate-500 bg-white dark:bg-black dark:text-blue-500 uppercase last:mr-0 mr-2 mt-2">
                    Menus
                  </span>
                  <span className="text-xs font-semibold inline-block py-1 px-2 rounded-full text-slate-500 bg-white dark:bg-black dark:text-blue-500 uppercase last:mr-0 mr-2 mt-2">
                    Modals
                  </span>
                  <span className="text-xs font-semibold inline-block py-1 px-2 rounded-full text-slate-500 bg-white dark:bg-black dark:text-blue-500 uppercase last:mr-0 mr-2 mt-2">
                    Navbars
                  </span>
                  <span className="text-xs font-semibold inline-block py-1 px-2 rounded-full text-slate-500 bg-white dark:bg-black dark:text-blue-500 uppercase last:mr-0 mr-2 mt-2">
                    Popovers
                  </span>
                  <span className="text-xs font-semibold inline-block py-1 px-2 rounded-full text-slate-500 bg-white dark:bg-black dark:text-blue-500 uppercase last:mr-0 mr-2 mt-2">
                    Tabs
                  </span>
                  <span className="text-xs font-semibold inline-block py-1 px-2 rounded-full text-slate-500 bg-white dark:bg-black dark:text-blue-500 uppercase last:mr-0 mr-2 mt-2">
                    Tooltips
                  </span>
                </div>
                <a
                  className="font-bold text-slate-700 hover:text-slate-500 dark:text-slate-300 dark:hover:text-slate-500 ease-linear transition-all duration-150"
                  href="/learning-lab/tailwind-starter-kit/documentation/vue/alerts"
                >
                  View all
                  <i className="fa fa-angle-double-right ml-1 leading-relaxed"></i>
                </a>
              </div>
            </div>
          </div>
        </section>
      </main>
      <MainFooter />
    </React.Fragment>
  );
}
