import * as React from 'react';
import { useDispatch } from 'react-redux';
import Head from 'next/head';
import {
  CodeIcon,
  CogIcon,
  ChartBarIcon,
  PuzzleIcon,
} from '@heroicons/react/outline';

import { request_refresh } from 'src/actions/auth';
import MainNavbar from 'src/components/navbars/MainNavbar';
import MainFooter from 'src/components/MainFooter';
import HomePageSvg from 'src/svgs/homepageSVG';

export default function Home() {
  const dispatch = useDispatch();

  React.useEffect(() => {
    if (dispatch && dispatch !== null && dispatch !== undefined)
      dispatch(request_refresh());
  }, [dispatch]);

  return (
    <React.Fragment>
      <Head>
        <title>Web Development solutions for growing businesses</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div>
        <MainNavbar />
        <div className="max-w-7xl h-3/4 z-10 lg:flex mx-auto bg-inherit md:justify-center md:items-center my-10 md:my-20 ">
          <div className="w-auto md:mx-auto md:w-3/4 lg:w-1/2 p-10">
            <h1 className="text-4xl mb-7 lg:text-5xl md:leading-normal font-bold ">
              <span className="text-slate-800 dark:text-white">
                We make your business look good
              </span>{' '}
              <span className="text-blue-600">online.</span>
            </h1>
            <p className="text-xl mt-4">
              {' '}
              Offering scalable and manageable web development solutions with
              the latest technology to let your business have a unique online
              representation.{' '}
            </p>
          </div>
          <div className="w-1/2 p-10 h-3/4 hidden lg:flex justify-center items-center">
            <HomePageSvg height="500" width="500" />
          </div>
        </div>
        <section className=" md:mt-52 mt-52 max-w-full mx-auto pb-32 relative bg-slate-100 dark:bg-gray-900">
          <div
            className="-mt-20 top-0 bottom-auto left-0 right-0 w-full absolute"
            style={{ height: '80px' }}
          >
            <svg
              className="absolute bottom-0 overflow-hidden"
              xmlns="http://www.w3.org/2000/svg"
              preserveAspectRatio="none"
              version="1.1"
              viewBox="0 0 2560 100"
              x="0"
              y="0"
            >
              <polygon
                className="text-slate-100 dark:text-gray-900 fill-current"
                points="2560 0 2560 100 0 100"
              ></polygon>
            </svg>
          </div>
          <div />
          <div className="container mx-auto mt-30">
            <div className="flex flex-wrap items-center">
              <div className="w-11/12 md:w-6/12 lg:w-4/12 px-12 md:px-4 mr-auto ml-auto -mt-32">
                <div className="relative flex flex-col min-w-0 break-words w-full mb-6 shadow-lg rounded-lg bg-blue-500">
                  <img
                    alt="..."
                    src="/macbook_index.png"
                    className="w-full align-middle rounded-t-lg"
                  />
                  <blockquote className="relative p-8 mb-4">
                    <svg
                      preserveAspectRatio="none"
                      xmlns="http://www.w3.org/2000/svg"
                      viewBox="0 0 583 95"
                      className="absolute left-0 w-full block"
                      style={{ height: '95px', top: '-94px' }}
                    >
                      <polygon
                        points="-30,95 583,95 583,65"
                        className="text-blue-500 fill-current"
                      ></polygon>
                    </svg>
                    <h4 className="text-xl font-bold text-white">
                      Web Design & Development
                    </h4>
                    <p className="text-md font-light mt-2 text-white">
                      Client-focused, customer-centric, creating website
                      solutions that deliver tangible business results,
                      Appnovation's web developers helps brands the
                      ever-changing digital landscape.
                    </p>
                  </blockquote>
                </div>
              </div>
              <div className="w-full md:w-6/12 px-4">
                <div className="flex flex-wrap">
                  <div className="w-full md:w-6/12 px-4">
                    <div className="relative flex flex-col mt-4">
                      <div className="px-4 py-5 flex-auto">
                        <div className="text-slate-500 p-3 text-center inline-flex items-center justify-center w-12 h-12 mb-5 shadow-lg rounded-full bg-white dark:bg-black border-2 border-blue-500">
                          <CogIcon />
                        </div>
                        <h6 className="text-xl mb-1 font-semibold">
                          Back-end development
                        </h6>
                        <p className="mb-4 text-slate-500">
                          we accurately implement the business logic of your web
                          app on the back end. We rely on proven frameworks to
                          ensure fast and quality coding.
                        </p>
                      </div>
                    </div>
                    <div className="relative flex flex-col min-w-0">
                      <div className="px-4 py-5 flex-auto">
                        <div className="text-slate-500 p-3 text-center inline-flex items-center justify-center w-12 h-12 mb-5 shadow-lg rounded-full bg-white dark:bg-black border-2 border-blue-500">
                          <CodeIcon />
                        </div>
                        <h6 className="text-xl mb-1 font-semibold">
                          Front-end design and development
                        </h6>
                        <p className="mb-4 text-slate-500">
                          Our web designers closely analyze the user audience to
                          understand their needs and reflect these findings in
                          UI design. Having agreed on the look and feel of a web
                          app with project stakeholders, we bring it to life
                          with front-end coding.
                        </p>
                      </div>
                    </div>
                  </div>
                  <div className="w-full md:w-6/12 px-4">
                    <div className="relative flex flex-col min-w-0 mt-4">
                      <div className="px-4 py-5 flex-auto">
                        <div className="text-slate-500 p-3 text-center inline-flex items-center justify-center w-12 h-12 mb-5 shadow-lg rounded-full bg-white dark:bg-black border-2 border-blue-500">
                          <ChartBarIcon />
                        </div>
                        <h6 className="text-xl mb-1 font-semibold">
                          Business analysis
                        </h6>
                        <p className="mb-4 text-slate-500">
                          Our business analysts focus on the needs of your
                          target audience to perform requirements engineering
                          and outline the scope of the solution. They also
                          bridge the gap between business stakeholders and an IT
                          team to keep all the involved parties aligned.
                        </p>
                      </div>
                    </div>
                    <div className="relative flex flex-col min-w-0">
                      <div className="px-4 py-5 flex-auto">
                        <div className="text-slate-500 p-3 text-center inline-flex items-center justify-center w-12 h-12 mb-5 shadow-lg rounded-full bg-white dark:bg-black border-2 border-blue-500">
                          <PuzzleIcon />
                        </div>
                        <h6 className="text-xl mb-1 font-semibold">
                          Integration
                        </h6>
                        <p className="mb-4 text-slate-500">
                          We set up APIs to integrate your web app with
                          corporate or third-party systems and services. App
                          integration ensures immediate data synchronization
                          across systems.
                        </p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="container mx-auto overflow-hidden pb-20">
            <div className="flex flex-wrap items-center lg:pt-24">
              <div className="w-full md:w-6/12 px-4 mr-auto ml-auto mt-32">
                <div className="justify-center flex flex-wrap relative">
                  <div className="my-4 w-full lg:w-6/12 px-4">
                    <div className="bg-sky-500 shadow-lg rounded-lg text-center p-8">
                      <div className="shadow-md rounded-full h-16 w-16 mx-auto p-1 bg-white flex justify-center items-center">
                        <img
                          alt="..."
                          className="h-10 w-10"
                          src="/react_index.png"
                        />
                      </div>
                      <noscript>
                        <div className="shadow-md rounded-full h-16 w-16 mx-auto p-1 bg-white flex justify-center items-center">
                          <img
                            alt="..."
                            className="h-10 w-10"
                            src="/react_index.png"
                          />
                        </div>
                      </noscript>
                      <p className="text-lg text-white mt-4 font-semibold">
                        ReactJS
                      </p>
                      <p className="text-base text-white opacity-75 mt-2">
                        A JavaScript library for building user interfaces
                        maintaned by Facebook and community of developers.
                      </p>
                    </div>
                    <div className="bg-emerald-800 shadow-lg rounded-lg text-center p-8 mt-8">
                      <div className="shadow-md rounded-full h-16 w-16 mx-auto p-1 bg-white flex justify-center items-center">
                        <img
                          alt="..."
                          className="h-10 w-10"
                          src="/django_index.png"
                        />
                      </div>
                      <noscript>
                        <div className="shadow-md rounded-full h-16 w-16 mx-auto p-1 bg-white flex justify-center items-center">
                          <img
                            alt="..."
                            className="h-10 w-10"
                            src="/django_index.png"
                          />
                        </div>
                      </noscript>
                      <p className="text-lg text-white mt-4 font-semibold">
                        Django
                      </p>
                      <p className="text-base text-white opacity-75 mt-2">
                        Django is an open source high-level Python web framework
                        that encourages rapid development and clean, pragmatic
                        design.
                      </p>
                    </div>
                  </div>
                  <div className="my-4 w-full lg:w-6/12 px-4 lg:mt-16">
                    <div className="bg-orange-500 shadow-lg rounded-lg text-center p-8">
                      <div className="shadow-md rounded-full h-16 w-16 mx-auto p-1 bg-white flex justify-center items-center">
                        <img
                          alt="..."
                          className="h-10 w-10"
                          src="/javascript_index.png"
                        />
                      </div>
                      <noscript>
                        <div className="shadow-md rounded-full h-16 w-16 mx-auto p-1 bg-white flex justify-center items-center">
                          <img
                            alt="..."
                            className="h-10 w-10"
                            src="/javascript_index.png"
                          />
                        </div>
                      </noscript>
                      <p className="text-lg text-white mt-4 font-semibold">
                        JavaScript
                      </p>
                      <p className="text-base text-white opacity-75 mt-2">
                        Object-oriented programming language that conforms to
                        the ECMAScript specification.
                      </p>
                    </div>
                    <div className="bg-black shadow-lg rounded-lg text-center p-8 mt-8">
                      <div className="shadow-md rounded-full h-16 w-16 mx-auto p-1 bg-white flex justify-center items-center">
                        <img
                          alt="..."
                          className="h-10 w-10"
                          src="/nextjs_index.png"
                        />
                      </div>
                      <noscript>
                        <div className="shadow-md rounded-full h-16 w-16 mx-auto p-1 bg-white flex justify-center items-center">
                          <img
                            alt="..."
                            className="h-10 w-10"
                            src="/nextjs_index.png"
                          />
                        </div>
                      </noscript>
                      <p className="text-lg text-white mt-4 font-semibold">
                        Next.js
                      </p>
                      <p className="text-base text-white opacity-75 mt-2">
                        Next.js is an open source minimalistic framework for
                        server-rendered React applications as well as statically
                        exported React apps.
                      </p>
                    </div>
                  </div>
                </div>
              </div>
              <div className="w-full md:w-4/12 px-12 md:px-4 ml-auto mr-auto mt-32">
                {/* <div className="text-blue-500 border-2 border-blue-500 p-3 text-center inline-flex items-center justify-center w-16 h-16 mb-6 shadow-lg rounded-full bg-white dark:bg-black">
                  <CodeIcon className="w-8" />
                </div> */}
                <h3 className="text-3xl mb-2 font-semibold leading-normal">
                  The tech stack designed for building competitive products
                </h3>
                <p className="text-lg font-light leading-relaxed mt-4 mb-4 text-slate-600 dark:text-slate-300">
                  Just like you, we choose scalable and flexible technologies.
                  The engineering mindset our talents have already solved the
                  challenges of many clients. Unsure how to lead development
                  forward? Your future team will guide you to the most optimal
                  software solutions and strategies.
                </p>
                <p className="text-2xl font-light leading-relaxed mt-4 mb-4 text-slate-600 dark:text-slate-300">
                  Industry-focused Web Development
                </p>
                <div className="block pb-6">
                  <span className="text-xs font-semibold inline-block py-1 px-2 rounded-full text-slate-500 bg-white dark:bg-black dark:text-blue-500 uppercase last:mr-0 mr-2 mt-2">
                    Ecommerce
                  </span>
                  <span className="text-xs font-semibold inline-block py-1 px-2 rounded-full text-slate-500 bg-white dark:bg-black dark:text-blue-500 uppercase last:mr-0 mr-2 mt-2">
                    Websites
                  </span>
                  <span className="text-xs font-semibold inline-block py-1 px-2 rounded-full text-slate-500 bg-white dark:bg-black dark:text-blue-500 uppercase last:mr-0 mr-2 mt-2">
                    Landing pages
                  </span>
                  <span className="text-xs font-semibold inline-block py-1 px-2 rounded-full text-slate-500 bg-white dark:bg-black dark:text-blue-500 uppercase last:mr-0 mr-2 mt-2">
                    Web portals
                  </span>
                  <span className="text-xs font-semibold inline-block py-1 px-2 rounded-full text-slate-500 bg-white dark:bg-black dark:text-blue-500 uppercase last:mr-0 mr-2 mt-2">
                    Rest APIs
                  </span>
                  <span className="text-xs font-semibold inline-block py-1 px-2 rounded-full text-slate-500 bg-white dark:bg-black dark:text-blue-500 uppercase last:mr-0 mr-2 mt-2">
                    Web Applications
                  </span>
                </div>
                <a
                  className="font-bold text-slate-700 hover:text-slate-500 dark:text-slate-300 dark:hover:text-slate-500 ease-linear transition-all duration-150"
                  href="/"
                >
                  View all
                  <i className="fa fa-angle-double-right ml-1 leading-relaxed"></i>
                </a>
              </div>
            </div>
          </div>
        </section>
      </div>
      <MainFooter />
    </React.Fragment>
  );
}
