import * as React from 'react';
import { useDispatch } from 'react-redux';
import Head from 'next/head';

import { request_refresh } from 'src/actions/auth';
import MainNavbar from 'src/components/navbars/MainNavbar';
import UserSignIn from 'src/components/UserSignIn';
import ParticleBackground from 'src/components/particleBackground';

export default function LoginPage() {
  const dispatch = useDispatch();

  React.useEffect(() => {
    if (dispatch && dispatch !== null && dispatch !== undefined)
      dispatch(request_refresh());
  }, [dispatch]);

  return (
    <React.Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ParticleBackground />
      <MainNavbar />
      <main>
        <UserSignIn />
      </main>
    </React.Fragment>
  );
}
